### ISSUE TITLE
it is not downloading, host not found 

### ISSUE THREAD

**Issue by imranlashari** [akibtanjim/google-translate#1]
[Composer\Downloader\TransportException]
  The "http://repo.packagist.org/p/akibtanjim/google-translate%24179de9537bbd5eaee9fa5f401da558e76ba67705651b69002c8dee267f4889ae.json" file could not be downloaded: php_netw   
  ork_getaddresses: getaddrinfo failed: No such host is known.

**Comment by akibtanjim** [comment]
Not an issue related to this package as such closing this issue
