### ISSUE TITLE
Trying to access array offset on value of type null 

### ISSUE THREAD

**Issue by ComputerMaverick69** [akibtanjim/google-translate#2]
The translateText throws an error message when trying to translate from English to other languages using the package. Find attached a screenshot...
<img width="643" alt="Screenshot 2021-08-29 at 12 18 24 AM" src="https://user-images.githubusercontent.com/43058711/131227930-8681285a-b589-4652-bc54-46820f29f5b2.png">
<img width="1196" alt="Screenshot 2021-08-29 at 12 18 45 AM" src="https://user-images.githubusercontent.com/43058711/131227936-047e065e-0064-4ade-90de-729e8cdb0a6e.png">

**Comment by akibtanjim** [comment]
@ComputerMaverick69  hello there. Please provide the sentence you are trying to translate

**Comment by ComputerMaverick69** [comment]
> @ComputerMaverick69 hello there. Please provide the sentence you are trying to translate

I was already using the package and everything was working fine. It suddenly stopped working. I'm translating an entire website using the package so it would be difficult sharing the sentence. Some of the words are Sign In, Log Out, Dashboard, Settings

**Comment by akibtanjim** [comment]
@ComputerMaverick69 is the issue resolved?

**Comment by ComputerMaverick69** [comment]
> @ComputerMaverick69 is the issue resolved?

Yes i have been able to figure it out. A user's paragraph had the quote symbol which was interfering the that of the function translateText. Had to escape all such characters.
